"""backend listo

Revision ID: b65a4249a4bc
Revises: e9bce5ee0ba1
Create Date: 2026-02-02 17:41:36.037852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65a4249a4bc'
down_revision: Union[str, None] = 'e9bce5ee0ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('input_type', sa.Enum('TEXT', 'AUDIO', name='inputtype'), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('interpreted_data', sa.Text(), nullable=True),
    sa.Column('was_confirmed', sa.Boolean(), nullable=False),
    sa.Column('tasks_created', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_requests_created_at'), 'ai_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_requests_id'), 'ai_requests', ['id'], unique=False)
    op.create_index(op.f('ix_ai_requests_user_id'), 'ai_requests', ['user_id'], unique=False)
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_history_action'), 'task_history', ['action'], unique=False)
    op.create_index(op.f('ix_task_history_created_at'), 'task_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_history_id'), 'task_history', ['id'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_history_user_id'), 'task_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_user_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_created_at'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_action'), table_name='task_history')
    op.drop_table('task_history')
    op.drop_index(op.f('ix_ai_requests_user_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_created_at'), table_name='ai_requests')
    op.drop_table('ai_requests')
    # ### end Alembic commands ###
